// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "../bindings/Viem.res.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as SdkReactCore from "@dynamic-labs/sdk-react-core";

function requestInEffect(request, setState) {
  return function () {
    Core__Promise.$$catch(request.then(function (res) {
              setState(function (param) {
                    return {
                            TAG: "Data",
                            _0: res
                          };
                  });
            }), (function (exn) {
            console.error(exn);
            setState(function (param) {
                  return {
                          TAG: "Err",
                          _0: exn
                        };
                });
            return Promise.resolve();
          }));
  };
}

function useRequest0(request) {
  var match = React.useState(function () {
        return "Loading";
      });
  var partial_arg = requestInEffect(request, match[1]);
  React.useEffect(Curry.__1(partial_arg), []);
  return match[0];
}

function useRequest1(request, deps) {
  var match = React.useState(function () {
        return "Loading";
      });
  var partial_arg = requestInEffect(request, match[1]);
  React.useEffect(Curry.__1(partial_arg), deps);
  return match[0];
}

function useRequest2(request, deps) {
  var match = React.useState(function () {
        return "Loading";
      });
  var partial_arg = requestInEffect(request, match[1]);
  React.useEffect(Curry.__1(partial_arg), deps);
  return match[0];
}

function useRequest3(request, deps) {
  var match = React.useState(function () {
        return "Loading";
      });
  var partial_arg = requestInEffect(request, match[1]);
  React.useEffect(Curry.__1(partial_arg), deps);
  return match[0];
}

function useLatestGameId(user, mincomind) {
  return useRequest0(mincomind.read.getLatestGameId([user]));
}

function useGame(user, gameId, mincomind) {
  return useRequest3(mincomind.read.getGame([
                  user,
                  gameId
                ]), [
              user,
              gameId,
              mincomind
            ]);
}

function useWalletClient() {
  var match = React.useState(function () {
        return "Loading";
      });
  var setState = match[1];
  var state = match[0];
  var dynamicContext = SdkReactCore.useDynamicContext();
  var connector = Core__Option.flatMap(Caml_option.nullable_to_opt(dynamicContext.primaryWallet), (function (pw) {
          return Core__Option.map(Caml_option.nullable_to_opt(pw.connector), (function (c) {
                        return [
                                c,
                                pw.address
                              ];
                      }));
        }));
  React.useEffect((function () {
          var asyncFn = async function () {
            if (connector === undefined) {
              return ;
            }
            if (typeof state === "object") {
              return ;
            }
            var walletClient;
            try {
              walletClient = Viem.wrapWalletClient(connector[0].getWalletClient(), connector[1]);
            }
            catch (raw_exn){
              var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
              console.log("Failed to createWalletClientFromWallet", exn);
              return ;
            }
            console.log("Wallet client here", walletClient);
            return setState(function (param) {
                        return {
                                TAG: "Data",
                                _0: walletClient
                              };
                      });
          };
          asyncFn();
        }), [dynamicContext.primaryWallet]);
  return state;
}

export {
  requestInEffect ,
  useRequest0 ,
  useRequest1 ,
  useRequest2 ,
  useRequest3 ,
  useLatestGameId ,
  useGame ,
  useWalletClient ,
}
/* Viem Not a pure module */
