// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Mincomind from "../bindings/Mincomind.res.mjs";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";

function useRequest(request) {
  var match = React.useState(function () {
        return "Loading";
      });
  var setState = match[1];
  React.useEffect((function () {
          Core__Promise.$$catch(request.then(function (res) {
                    setState(function (param) {
                          return {
                                  TAG: "Data",
                                  _0: res
                                };
                        });
                  }), (function (exn) {
                  setState(function (param) {
                        return {
                                TAG: "Err",
                                _0: exn
                              };
                      });
                  return Promise.resolve();
                }));
        }), []);
  return match[0];
}

function useLatestGameId(user, client) {
  var mincoMind = Mincomind.getContract(client);
  return useRequest(mincoMind.read.getLatestGameId(user));
}

function useGame(user, gameId, client) {
  var mincoMind = Mincomind.getContract(client);
  return useRequest(mincoMind.read.getGame(user, gameId));
}

export {
  useRequest ,
  useLatestGameId ,
  useGame ,
}
/* react Not a pure module */
