// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./components/Game.res.mjs";
import * as Home from "./components/Home.res.mjs";
import * as Table from "./components/Table.res.mjs";
import * as React from "react";
import * as Mincomind from "./bindings/Mincomind.res.mjs";
import * as ContractHooks from "./hooks/ContractHooks.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var client = ContractHooks.useWalletClient();
  var match = React.useState(function () {
        return "Home";
      });
  var setPage = match[1];
  var tmp;
  if (typeof client !== "object") {
    tmp = "loading...";
  } else if (client.TAG === "Err") {
    tmp = "Error getting client check console...";
  } else {
    var walletClient = client._0;
    var mincomind = Mincomind.getContract(walletClient);
    var user = walletClient.account.address;
    switch (match[0]) {
      case "Home" :
          tmp = JsxRuntime.jsx(Home.make, {
                mincomind: mincomind,
                user: user
              });
          break;
      case "Game" :
          tmp = JsxRuntime.jsx(Game.make, {
                user: user,
                mincomind: mincomind
              });
          break;
      case "Leaderboard" :
          tmp = JsxRuntime.jsx(Table.make, {
                mincomind: mincomind,
                client: walletClient
              });
          break;
      
    }
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Home",
                              className: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 mx-2 rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Home";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Game",
                              className: "bg-blue-500 hover:bg-blue-700 text-white  py-2 px-4  mx-2 rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Game";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Leaderboard",
                              className: "bg-blue-500 hover:bg-blue-700 text-white  py-2 px-4  mx-2  rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Leaderboard";
                                      });
                                })
                            })
                      ],
                      className: "flex items-center w-full text-md"
                    }),
                tmp
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Game Not a pure module */
