// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./components/Game.res.mjs";
import * as ContractHooks from "./hooks/ContractHooks.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var client = ContractHooks.useWalletClient();
  var tmp;
  if (typeof client !== "object") {
    tmp = "loading...";
  } else if (client.TAG === "Err") {
    tmp = "Error getting client check console...";
  } else {
    var match = client._0;
    tmp = JsxRuntime.jsx(Game.make, {
          walletClient: match[0],
          publicClient: match[1]
        });
  }
  return JsxRuntime.jsx("div", {
              children: tmp,
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Game Not a pure module */
