// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./components/Game.res.mjs";
import * as Home from "./components/Home.res.mjs";
import * as Table from "./components/Table.res.mjs";
import * as React from "react";
import * as ContractHooks from "./hooks/ContractHooks.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var client = ContractHooks.useWalletClient();
  var match = React.useState(function () {
        return "Home";
      });
  var setPage = match[1];
  var tmp;
  switch (match[0]) {
    case "Home" :
        tmp = JsxRuntime.jsx(Home.make, {});
        break;
    case "Game" :
        tmp = typeof client !== "object" ? "loading..." : (
            client.TAG === "Err" ? "Error getting client check console..." : JsxRuntime.jsx(Game.make, {
                    walletClient: client._0
                  })
          );
        break;
    case "Leaderboard" :
        tmp = JsxRuntime.jsx(Table.make, {});
        break;
    
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Home",
                              className: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 mx-2 rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Home";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Game",
                              className: "bg-blue-500 hover:bg-blue-700 text-white  py-2 px-4  mx-2 rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Game";
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Leaderboard",
                              className: "bg-blue-500 hover:bg-blue-700 text-white  py-2 px-4  mx-2  rounded",
                              onClick: (function (param) {
                                  setPage(function (param) {
                                        return "Leaderboard";
                                      });
                                })
                            })
                      ],
                      className: "flex items-center w-full text-md"
                    }),
                tmp
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Game Not a pure module */
