// Generated by ReScript, PLEASE EDIT WITH CARE


var indexerEndpoint = "http://localhost:8080/v1/graphql";

var wssIndexerEndpoint = "wss://localhost:8080/v1/graphql";

export {
  indexerEndpoint ,
  wssIndexerEndpoint ,
}
/* No side effect */
