// Generated by ReScript, PLEASE EDIT WITH CARE


var indexerEndpoint = "https://indexer.bigdevenergy.link/f39d41d/v1/graphql";

var wssIndexerEndpoint = "wss://indexer.bigdevenergy.link/f39d41d/v1/graphql";

export {
  indexerEndpoint ,
  wssIndexerEndpoint ,
}
/* No side effect */
