// Generated by ReScript, PLEASE EDIT WITH CARE


var Ethereum = {};

var DynamicContextProvider = {};

var DynamicWidget = {};

var Hooks = {};

export {
  Ethereum ,
  DynamicContextProvider ,
  DynamicWidget ,
  Hooks ,
}
/* No side effect */
