// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "viem";
import * as AbiMjs from "./abi.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var address = Viem.getAddress("0x9502209a80dc5aEC0d29F2095610fA988000558e");

var abi = AbiMjs.abi;

function make(_0, _1, _2, _3) {
  return {
          _0: _0,
          _1: _1,
          _2: _2,
          _3: _3
        };
}

function fromArrayUnsafe(tAsArray) {
  return {
          _0: tAsArray[0],
          _1: tAsArray[1],
          _2: tAsArray[2],
          _3: tAsArray[3]
        };
}

function toArray(param) {
  return [
          param._0,
          param._1,
          param._2,
          param._3
        ];
}

var Guess = {
  make: make,
  fromArrayUnsafe: fromArrayUnsafe,
  toArray: toArray
};

var Clue = {};

function getContract(walletClient) {
  return Viem.getContract({
              address: address,
              abi: abi,
              client: {
                public: Caml_option.some(walletClient),
                wallet: Caml_option.some(walletClient)
              }
            });
}

export {
  address ,
  abi ,
  Guess ,
  Clue ,
  getContract ,
}
/* address Not a pure module */
