// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Viem from "viem";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

function getAddress(s) {
  var addr;
  try {
    addr = Viem.getAddress(s);
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    return {
            TAG: "Error",
            _0: exn
          };
  }
  return {
          TAG: "Ok",
          _0: addr
        };
}

export {
  getAddress ,
}
/* viem Not a pure module */
