name: Mincomind
description: Mincomind indexer
contracts:
  - name: Game
    handler: ./src/EventHandlers.ts
    events:
      - event: NewGame(address indexed player, uint32 gameId)
      - event: GameOutcome(address indexed player, uint32 gameId, uint8 points)
      - event: GuessAdded(address indexed player, uint32 gameId, uint8 numGuesses, uint8[4] guess)
      - event: FundsWithdrawn(address player, uint256 amount)
networks:
  - id: 9090 # Inco
    start_block: 2460116
    rpc_config:
      url: https://testnet.inco.org/
    contracts:
      - name: Game
        address: 0x4e099588EA51F450c9807Ba5E6295B8e71cf4610
