// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var playersQuery = "\nquery MyQuery {\n  Player(where: {active: {_eq: true}}, order_by: {points: desc}) {\n    id\n    points\n    numberOfGames\n  }\n}\n\n    ";

async function fetchPlayers(indexerEndpoint) {
  try {
    var resp = await fetch(indexerEndpoint, {
          method: "POST",
          body: Caml_option.some(JSON.stringify(Js_dict.fromList({
                        hd: [
                          "query",
                          playersQuery
                        ],
                        tl: /* [] */0
                      }))),
          headers: Caml_option.some(new Headers({
                    "x-hasura-role": "public",
                    "Content-type": "application/json"
                  }))
        });
    if (resp.ok) {
      return await resp.json();
    } else {
      return ;
    }
  }
  catch (exn){
    return ;
  }
}

export {
  playersQuery ,
  fetchPlayers ,
}
/* No side effect */
