// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function ActionButtons$NewGameActionButton(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("button", {
                    children: "New game",
                    className: "bg-blue-400 my-2 hover:bg-blue-300 text-sm text-white font-bold py-2 px-4 rounded pointer",
                    onClick: props.onAction
                  }),
              className: "flex justify-center space-x-4"
            });
}

var NewGameActionButton = {
  make: ActionButtons$NewGameActionButton
};

function ActionButtons$EndGameActionButton(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("button", {
                    children: "End game",
                    className: "bg-blue-400 my-2 hover:bg-blue-300 text-sm text-white font-bold py-2 px-4 rounded pointer",
                    onClick: props.onAction
                  }),
              className: "flex justify-center space-x-4"
            });
}

var EndGameActionButton = {
  make: ActionButtons$EndGameActionButton
};

function ActionButtons$WithdrawFundsActionButton(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("button", {
                    children: "Redeem points for pull",
                    className: "bg-blue-400 my-2 hover:bg-blue-300 text-sm text-white font-bold py-2 px-4 rounded pointer",
                    onClick: props.onAction
                  }),
              className: "flex justify-center space-x-4"
            });
}

var WithdrawFundsActionButton = {
  make: ActionButtons$WithdrawFundsActionButton
};

export {
  NewGameActionButton ,
  EndGameActionButton ,
  WithdrawFundsActionButton ,
}
/* react/jsx-runtime Not a pure module */
