// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: "New Game",
              onClick: (function (param) {
                  console.log("New Game");
                })
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
