// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ActionButtons from "./ActionButtons.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  var user = props.user;
  var mincomind = props.mincomind;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(ActionButtons.NewGameActionButton.make, {
                      onAction: (function (param) {
                          mincomind.write.newGame({
                                value: "1000000000000000"
                              });
                        })
                    }),
                JsxRuntime.jsx(ActionButtons.EndGameActionButton.make, {
                      onAction: (function (param) {
                          mincomind.write.endGame([user]);
                        })
                    }),
                JsxRuntime.jsx(ActionButtons.WithdrawFundsActionButton.make, {
                      onAction: (function (param) {
                          console.log("withdraw funds");
                        })
                    })
              ],
              className: "mx-auto"
            });
}

var make = Home;

export {
  make ,
}
/* ActionButtons Not a pure module */
