// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ActionButtons from "./ActionButtons.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(ActionButtons.NewGameActionButton.make, {
                      onAction: (function (param) {
                          console.log("new game");
                        })
                    }),
                JsxRuntime.jsx(ActionButtons.EndGameActionButton.make, {
                      onAction: (function (param) {
                          console.log("end game");
                        })
                    }),
                JsxRuntime.jsx(ActionButtons.WithdrawFundsActionButton.make, {
                      onAction: (function (param) {
                          console.log("withdraw funds");
                        })
                    })
              ],
              className: "mx-auto"
            });
}

var make = Home;

export {
  make ,
}
/* ActionButtons Not a pure module */
