// Generated by ReScript, PLEASE EDIT WITH CARE

import ClientJs from "./client.js";

function client(prim) {
  return ClientJs();
}

var Provider = {};

export {
  client ,
  Provider ,
}
/* ./client.js Not a pure module */
